/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CRouteImport } from './routes/c'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as CIndexRouteImport } from './routes/c.index'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CRoute,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => CRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c': typeof CRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/c/': typeof CIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/c': typeof CIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c': typeof CRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/c/': typeof CIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/c' | '/api/chat' | '/api/tts' | '/c/$threadId' | '/c/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/chat' | '/api/tts' | '/c/$threadId' | '/c'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/c'
    | '/api/chat'
    | '/api/tts'
    | '/c/$threadId'
    | '/c/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CRoute: typeof CRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof CRoute
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof CRoute
    }
  }
}

interface CRouteChildren {
  CThreadIdRoute: typeof CThreadIdRoute
  CIndexRoute: typeof CIndexRoute
}

const CRouteChildren: CRouteChildren = {
  CThreadIdRoute: CThreadIdRoute,
  CIndexRoute: CIndexRoute,
}

const CRouteWithChildren = CRoute._addFileChildren(CRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CRoute: CRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
