/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminTopupsRouteImport } from './routes/admin.topups'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardApiRouteImport } from './routes/dashboard.api'
import { Route as DashboardApiDocsRouteImport } from './routes/dashboard.api-docs'
import { Route as DashboardBuyRouteImport } from './routes/dashboard.buy'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardPackagesRouteImport } from './routes/dashboard.packages'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardStoreRouteImport } from './routes/dashboard.store'
import { Route as DashboardTrackRouteImport } from './routes/dashboard.track'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as AdminResellersUserIdRouteImport } from './routes/admin.resellers.$userId'
import { Route as ApiV1BalanceRouteImport } from './routes/api/v1/balance'
import { Route as ApiV1OrdersRouteImport } from './routes/api/v1/orders'
import { Route as ApiV1PackagesRouteImport } from './routes/api/v1/packages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiRoute = DashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiDocsRoute = DashboardApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuyRoute = DashboardBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPackagesRoute = DashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrackRoute = DashboardTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminResellersUserIdRoute = AdminResellersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminResellersRoute,
} as any)
const ApiV1BalanceRoute = ApiV1BalanceRouteImport.update({
  id: '/api/v1/balance',
  path: '/api/v1/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersRoute = ApiV1OrdersRouteImport.update({
  id: '/api/v1/orders',
  path: '/api/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PackagesRoute = ApiV1PackagesRouteImport.update({
  id: '/api/v1/packages',
  path: '/api/v1/packages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/api-docs': typeof DashboardApiDocsRoute
  '/dashboard/buy': typeof DashboardBuyRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/resellers/$userId': typeof AdminResellersUserIdRoute
  '/api/v1/balance': typeof ApiV1BalanceRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/api-docs': typeof DashboardApiDocsRoute
  '/dashboard/buy': typeof DashboardBuyRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/resellers/$userId': typeof AdminResellersUserIdRoute
  '/api/v1/balance': typeof ApiV1BalanceRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/api-docs': typeof DashboardApiDocsRoute
  '/dashboard/buy': typeof DashboardBuyRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/resellers/$userId': typeof AdminResellersUserIdRoute
  '/api/v1/balance': typeof ApiV1BalanceRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/topups'
    | '/admin/withdrawals'
    | '/dashboard/api'
    | '/dashboard/api-docs'
    | '/dashboard/buy'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/packages'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/track'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/admin/resellers/$userId'
    | '/api/v1/balance'
    | '/api/v1/orders'
    | '/api/v1/packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/topups'
    | '/admin/withdrawals'
    | '/dashboard/api'
    | '/dashboard/api-docs'
    | '/dashboard/buy'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/packages'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/track'
    | '/dashboard/wallet'
    | '/admin'
    | '/dashboard'
    | '/admin/resellers/$userId'
    | '/api/v1/balance'
    | '/api/v1/orders'
    | '/api/v1/packages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/topups'
    | '/admin/withdrawals'
    | '/dashboard/api'
    | '/dashboard/api-docs'
    | '/dashboard/buy'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/packages'
    | '/dashboard/settings'
    | '/dashboard/store'
    | '/dashboard/track'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/admin/resellers/$userId'
    | '/api/v1/balance'
    | '/api/v1/orders'
    | '/api/v1/packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiV1BalanceRoute: typeof ApiV1BalanceRoute
  ApiV1OrdersRoute: typeof ApiV1OrdersRoute
  ApiV1PackagesRoute: typeof ApiV1PackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api': {
      id: '/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof DashboardApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-docs': {
      id: '/dashboard/api-docs'
      path: '/api-docs'
      fullPath: '/dashboard/api-docs'
      preLoaderRoute: typeof DashboardApiDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buy': {
      id: '/dashboard/buy'
      path: '/buy'
      fullPath: '/dashboard/buy'
      preLoaderRoute: typeof DashboardBuyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/packages': {
      id: '/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/track': {
      id: '/dashboard/track'
      path: '/track'
      fullPath: '/dashboard/track'
      preLoaderRoute: typeof DashboardTrackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/resellers/$userId': {
      id: '/admin/resellers/$userId'
      path: '/$userId'
      fullPath: '/admin/resellers/$userId'
      preLoaderRoute: typeof AdminResellersUserIdRouteImport
      parentRoute: typeof AdminResellersRoute
    }
    '/api/v1/balance': {
      id: '/api/v1/balance'
      path: '/api/v1/balance'
      fullPath: '/api/v1/balance'
      preLoaderRoute: typeof ApiV1BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders': {
      id: '/api/v1/orders'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders'
      preLoaderRoute: typeof ApiV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/packages': {
      id: '/api/v1/packages'
      path: '/api/v1/packages'
      fullPath: '/api/v1/packages'
      preLoaderRoute: typeof ApiV1PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminResellersRouteChildren {
  AdminResellersUserIdRoute: typeof AdminResellersUserIdRoute
}

const AdminResellersRouteChildren: AdminResellersRouteChildren = {
  AdminResellersUserIdRoute: AdminResellersUserIdRoute,
}

const AdminResellersRouteWithChildren = AdminResellersRoute._addFileChildren(
  AdminResellersRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminResellersRoute: typeof AdminResellersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminResellersRoute: AdminResellersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardApiRoute: typeof DashboardApiRoute
  DashboardApiDocsRoute: typeof DashboardApiDocsRoute
  DashboardBuyRoute: typeof DashboardBuyRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPackagesRoute: typeof DashboardPackagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoreRoute: typeof DashboardStoreRoute
  DashboardTrackRoute: typeof DashboardTrackRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiRoute: DashboardApiRoute,
  DashboardApiDocsRoute: DashboardApiDocsRoute,
  DashboardBuyRoute: DashboardBuyRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPackagesRoute: DashboardPackagesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoreRoute: DashboardStoreRoute,
  DashboardTrackRoute: DashboardTrackRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiV1BalanceRoute: ApiV1BalanceRoute,
  ApiV1OrdersRoute: ApiV1OrdersRoute,
  ApiV1PackagesRoute: ApiV1PackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
